// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Url struct {
	ID       int64  `db:"id" json:"id"`
	ShortUrl string `db:"short_url" json:"short_url"`
	LongUrl  string `db:"long_url" json:"long_url"`
}
